name: xi
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  # native_dio_adapter: ^1.5.0
  xml2json: ^6.2.7
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  awesome_dio_interceptor: ^1.3.0

  # dio_cache_interceptor: ^4.0.3
  # dio_cache_interceptor:
  #   git:
  #     url: https://github.com/waifu-project/dart_http_cache
  #     path: dio_cache_interceptor

  path_provider: ^2.1.5
  jsonc: ^0.0.3
  path: ^1.9.1
  html_unescape: ^2.0.0
  equatable: ^2.0.7

    # flutter_js: ^0.8.5
  flutter_js:
    git: https://github.com/yhsj0919/flutter_js

  dart_qjson: ^1.0.2

flutter:
  assets:
    - assets/js/